# Generated by Django 6.0.4 on 2026-04-14 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=256)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('supplier', models.CharField(blank=True, max_length=256)),
                ('borrowed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('application_number', models.CharField(blank=True, max_length=128, unique=True)),
                ('first_name', models.CharField(max_length=128)),
                ('middle_name', models.CharField(blank=True, max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('gender', models.CharField(max_length=32)),
                ('role', models.CharField(choices=[('Student', 'Student'), ('Instructor', 'Instructor')], default='Student', max_length=24)),
                ('date_enrolled', models.DateField(auto_now_add=True)),
                ('current_belt_rank', models.CharField(blank=True, max_length=128)),
                ('club_branch', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='StanceEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stance_type', models.CharField(max_length=128)),
                ('score', models.IntegerField()),
                ('remarks', models.TextField(blank=True)),
                ('date_evaluated', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stance_evaluations', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('venue', models.CharField(max_length=256)),
                ('session_type', models.CharField(choices=[('regular', 'Regular'), ('seminar', 'Seminar'), ('competition prep', 'Competition Prep')], max_length=64)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('sale_date', models.DateField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='students.inventory')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('occupation', models.CharField(blank=True, max_length=128)),
                ('civil_status', models.CharField(blank=True, max_length=64)),
                ('build', models.CharField(blank=True, max_length=64)),
                ('complexion', models.CharField(blank=True, max_length=64)),
                ('nationality', models.CharField(blank=True, max_length=128)),
                ('hair_color', models.CharField(blank=True, max_length=128)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_info', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_fee', models.FloatField(default=0.0)),
                ('monthly_fee', models.FloatField(default=0.0)),
                ('testing_fee', models.FloatField(default=0.0)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('amount_paid', models.FloatField(default=0.0)),
                ('payment_status', models.CharField(blank=True, max_length=64)),
                ('payment_mode', models.CharField(blank=True, max_length=64)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('announcement', 'Announcement')], max_length=64)),
                ('message', models.TextField()),
                ('date_sent', models.DateField()),
                ('recipient', models.CharField(max_length=256)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(choices=[('New', 'New'), ('Renewal', 'Renewal'), ('Competitor', 'Competitor')], max_length=32)),
                ('membership_status', models.CharField(max_length=64)),
                ('membership_year', models.IntegerField()),
                ('membership_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_a', models.IntegerField()),
                ('score_b', models.IntegerField()),
                ('match_date', models.DateField()),
                ('category', models.CharField(max_length=128)),
                ('student_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_a', to='students.student')),
                ('student_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_b', to='students.student')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_won', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='KarateBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_club', models.CharField(blank=True, max_length=256)),
                ('karate_style', models.CharField(blank=True, max_length=256)),
                ('previous_rank', models.CharField(blank=True, max_length=128)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karate_backgrounds', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kata_score', models.IntegerField()),
                ('kumite_score', models.IntegerField()),
                ('discipline_score', models.IntegerField()),
                ('remarks', models.TextField(blank=True)),
                ('date_evaluated', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_ratings', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='FaceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_encoding', models.TextField(blank=True)),
                ('image_path', models.CharField(blank=True, max_length=512)),
                ('face_angle', models.CharField(blank=True, choices=[('Front', 'Front'), ('Left', 'Left'), ('Right', 'Right')], max_length=32)),
                ('date_registered', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_data', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_name', models.CharField(max_length=256)),
                ('relationship', models.CharField(max_length=128)),
                ('emergency_address', models.TextField(blank=True)),
                ('emergency_contact_number', models.CharField(max_length=64)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(blank=True, max_length=64)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('recognition_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(blank=True, max_length=128)),
                ('street', models.CharField(blank=True, max_length=256)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('full_address', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='students.student')),
            ],
        ),
    ]
