# Generated by Django 6.0.4 on 2026-04-14 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('announcement', 'Announcement'), ('alert', 'Alert'), ('success', 'Success'), ('info', 'Info'), ('product_ordered', 'Product Ordered'), ('student_registered', 'Student Registered'), ('staff_registered', 'Staff Registered'), ('parent_registered', 'Parent Registered')], max_length=64),
        ),
        migrations.CreateModel(
            name='SystemID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('id_type', models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor')], max_length=32)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('assigned', 'Assigned')], default='generated', max_length=32)),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('assigned_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_ids', to='students.student')),
            ],
            options={
                'ordering': ['-date_issued', 'code'],
            },
        ),
    ]
