# Generated by Django 6.0.4 on 2026-05-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_notification_notification_type_systemid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemid',
            name='id_type',
            field=models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor'), ('admin', 'Admin'), ('parent', 'Parent')], max_length=32),
        ),
    ]
