# Generated by Django 6.0.4 on 2026-05-07 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_systemid_id_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='students.student'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('seminar', 'Seminar'), ('tournament', 'Tournament'), ('competition prep', 'Competition Prep')], max_length=64),
        ),
    ]
