# Generated by Django 6.0.4 on 2026-05-08 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_session_instructor_alter_session_session_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stanceevaluation',
            name='analysis_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stanceevaluation',
            name='evaluated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stance_evaluations_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PoseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stance_label', models.CharField(max_length=128)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='pose_templates/')),
                ('landmarks', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pose_templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
