# Generated by Django 6.0.4 on 2026-05-09 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_stanceevaluation_analysis_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posetemplate',
            name='stance_label',
            field=models.CharField(choices=[('Kiba-dachi / Horse riding stance', 'Kiba-dachi / Horse riding stance'), ('Nekoashi-dachi / Cat stance', 'Nekoashi-dachi / Cat stance'), ('Sanchin-dachi / Hourglass/three-point stance', 'Sanchin-dachi / Hourglass/three-point stance'), ('Heisoku-dachi / Formal attention stance', 'Heisoku-dachi / Formal attention stance'), ('Age-uke / Rising block', 'Age-uke / Rising block'), ('Gedan-barai / Downward block', 'Gedan-barai / Downward block'), ('Soto-uke / Outside-to-inside block', 'Soto-uke / Outside-to-inside block'), ('Uchi-uke / Inside-to-outside block', 'Uchi-uke / Inside-to-outside block'), ('Shuto-uke / Knife hand block', 'Shuto-uke / Knife hand block'), ('Morote-uke / Augmented/two-hand block', 'Morote-uke / Augmented/two-hand block'), ('Choku-zuki / Straight punch', 'Choku-zuki / Straight punch'), ('Oi-zuki / Lunge punch', 'Oi-zuki / Lunge punch'), ('Gyaku-zuki / Reverse punch', 'Gyaku-zuki / Reverse punch'), ('Kizami-zuki / Jab punch', 'Kizami-zuki / Jab punch'), ('Uraken-uchi / Backfist strike', 'Uraken-uchi / Backfist strike'), ('Shuto-uchi / Knife hand strike', 'Shuto-uchi / Knife hand strike'), ('Empi-uchi / Elbow strike', 'Empi-uchi / Elbow strike'), ('Haito-uchi / Ridge hand strike', 'Haito-uchi / Ridge hand strike'), ('Mae-geri / Front kick', 'Mae-geri / Front kick'), ('Mawashi-geri / Roundhouse kick', 'Mawashi-geri / Roundhouse kick'), ('Yoko-geri Keage / Side snap kick', 'Yoko-geri Keage / Side snap kick'), ('Yoko-geri Kekomi / Side thrust kick', 'Yoko-geri Kekomi / Side thrust kick'), ('Ushiro-geri / Back kick', 'Ushiro-geri / Back kick'), ('Fumikomi / Stomp kick', 'Fumikomi / Stomp kick'), ('Hiza-geri / Knee kick', 'Hiza-geri / Knee kick'), ('Tobi-geri / Jumping kick', 'Tobi-geri / Jumping kick')], max_length=128),
        ),
        migrations.CreateModel(
            name='BeltProgressionIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_belt', models.CharField(blank=True, max_length=128)),
                ('target_belt', models.CharField(blank=True, max_length=128)),
                ('readiness_status', models.CharField(choices=[('not_ready', 'Not Ready'), ('in_progress', 'In Progress'), ('ready', 'Ready for Testing'), ('tested', 'Tested - Awaiting Decision'), ('promoted', 'Promoted')], default='not_ready', max_length=32)),
                ('kata_readiness', models.FloatField(default=0.0)),
                ('kumite_readiness', models.FloatField(default=0.0)),
                ('discipline_readiness', models.FloatField(default=0.0)),
                ('attendance_readiness', models.FloatField(default=0.0)),
                ('overall_readiness_percentage', models.FloatField(default=0.0)),
                ('kata_requirement', models.FloatField(default=75.0)),
                ('kumite_requirement', models.FloatField(default=70.0)),
                ('discipline_requirement', models.FloatField(default=80.0)),
                ('attendance_requirement', models.FloatField(default=85.0)),
                ('eligible_since', models.DateField(blank=True, null=True)),
                ('last_assessment_date', models.DateField(auto_now=True)),
                ('estimated_promotion_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belt_progression_indicators', to='students.student')),
            ],
            options={
                'ordering': ['-last_assessment_date'],
                'indexes': [models.Index(fields=['student', 'readiness_status'], name='students_be_student_0437f7_idx')],
            },
        ),
        migrations.CreateModel(
            name='KataRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pose_evaluation_avg', models.FloatField(default=0.0)),
                ('instructor_kata_score', models.FloatField(default=0.0)),
                ('combined_kata_score', models.FloatField(default=0.0)),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('month_year', models.CharField(blank=True, max_length=7)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kata_ratings', to='students.student')),
            ],
            options={
                'ordering': ['-date_recorded'],
                'indexes': [models.Index(fields=['student', 'date_recorded'], name='students_ka_student_7f8274_idx')],
            },
        ),
        migrations.CreateModel(
            name='KumiteRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_avg_score', models.FloatField(default=0.0)),
                ('instructor_kumite_score', models.FloatField(default=0.0)),
                ('combined_kumite_score', models.FloatField(default=0.0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('month_year', models.CharField(blank=True, max_length=7)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kumite_ratings', to='students.student')),
            ],
            options={
                'ordering': ['-date_recorded'],
                'indexes': [models.Index(fields=['student', 'date_recorded'], name='students_ku_student_0b6cf5_idx')],
            },
        ),
        migrations.CreateModel(
            name='PerformanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('overall', 'Overall')], max_length=16)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('kata_average', models.FloatField(default=0.0)),
                ('kumite_average', models.FloatField(default=0.0)),
                ('discipline_average', models.FloatField(default=0.0)),
                ('overall_average', models.FloatField(default=0.0)),
                ('kata_trend', models.FloatField(default=0.0)),
                ('kumite_trend', models.FloatField(default=0.0)),
                ('discipline_trend', models.FloatField(default=0.0)),
                ('overall_trend', models.FloatField(default=0.0)),
                ('sessions_attended', models.IntegerField(default=0)),
                ('evaluations_count', models.IntegerField(default=0)),
                ('matches_participated', models.IntegerField(default=0)),
                ('strength_area', models.CharField(blank=True, max_length=64)),
                ('improvement_area', models.CharField(blank=True, max_length=64)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_summaries', to='students.student')),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['student', 'period', 'start_date'], name='students_pe_student_01b87d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProgressionInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('strength', 'Strength'), ('weakness', 'Weakness'), ('trend', 'Trend'), ('recommendation', 'Recommendation'), ('milestone', 'Milestone')], max_length=32)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('metric_name', models.CharField(blank=True, max_length=128)),
                ('metric_value', models.FloatField(default=0.0)),
                ('metric_history', models.JSONField(blank=True, default=dict)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progression_insights', to='students.student')),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['student', 'insight_type'], name='students_pr_student_b22aee_idx')],
            },
        ),
    ]
