# Generated by Django 5.2.14 on 2026-05-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_cart_cartitem_order_orderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
