# Generated by Django 6.0.4 on 2026-05-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_parentstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('announcement', 'Announcement'), ('alert', 'Alert'), ('success', 'Success'), ('info', 'Info'), ('product_ordered', 'Product Ordered'), ('student_registered', 'Student Registered'), ('staff_registered', 'Staff Registered'), ('parent_registered', 'Parent Registered'), ('schedule_created', 'Schedule Created'), ('schedule_updated', 'Schedule Updated'), ('class_cancelled', 'Class Cancelled'), ('tournament_announcement', 'Tournament Announcement'), ('belt_exam_scheduled', 'Belt Exam Scheduled'), ('belt_exam_reminder', 'Belt Exam Reminder'), ('marked_absent', 'Marked Absent'), ('attendance_streak_achieved', 'Attendance Streak Achieved'), ('grade_posted', 'Grade Posted'), ('belt_promotion_eligibility_achieved', 'Belt Promotion Eligibility Achieved'), ('new_rank_achieved', 'New Rank Achieved'), ('level_increased', 'Level Increased'), ('achievement_unlocked', 'Achievement Unlocked'), ('streak_bonus_earned', 'Streak Bonus Earned'), ('leaderboard_rank_increased', 'Leaderboard Rank Increased'), ('profile_updated', 'Profile Updated'), ('tournament_added', 'Tournament Added'), ('seminar_added', 'Seminar Added'), ('attendance_recorded', 'Attendance Recorded'), ('pose_evaluation_completed', 'Pose Evaluation Completed'), ('grading_submitted', 'Grading Submitted'), ('promotion_eligible', 'Promotion Eligible'), ('grade_updated', 'Grade Updated'), ('match_result_recorded', 'Match Result Recorded'), ('top_performers_identified', 'Top Performers Identified'), ('weekly_report_generated', 'Weekly Report Generated')], max_length=64),
        ),
    ]
