# Generated by Django 6.0.4 on 2026-05-25 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beltprogressionindicator',
            name='current_belt',
            field=models.CharField(blank=True, choices=[('White Belt', 'White Belt'), ('Yellow Belt', 'Yellow Belt'), ('Orange Belt', 'Orange Belt'), ('Green Belt', 'Green Belt'), ('Purple Belt', 'Purple Belt'), ('1st Class Purple Belt', '1st Class Purple Belt'), ('Brown Belt', 'Brown Belt'), ('1st Class Brown Belt', '1st Class Brown Belt'), ('2nd Class Brown Belt', '2nd Class Brown Belt'), ('Black Belt', 'Black Belt')], max_length=128),
        ),
        migrations.AlterField(
            model_name='beltprogressionindicator',
            name='target_belt',
            field=models.CharField(blank=True, choices=[('White Belt', 'White Belt'), ('Yellow Belt', 'Yellow Belt'), ('Orange Belt', 'Orange Belt'), ('Green Belt', 'Green Belt'), ('Purple Belt', 'Purple Belt'), ('1st Class Purple Belt', '1st Class Purple Belt'), ('Brown Belt', 'Brown Belt'), ('1st Class Brown Belt', '1st Class Brown Belt'), ('2nd Class Brown Belt', '2nd Class Brown Belt'), ('Black Belt', 'Black Belt')], max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_belt_rank',
            field=models.CharField(blank=True, choices=[('White Belt', 'White Belt'), ('Yellow Belt', 'Yellow Belt'), ('Orange Belt', 'Orange Belt'), ('Green Belt', 'Green Belt'), ('Purple Belt', 'Purple Belt'), ('1st Class Purple Belt', '1st Class Purple Belt'), ('Brown Belt', 'Brown Belt'), ('1st Class Brown Belt', '1st Class Brown Belt'), ('2nd Class Brown Belt', '2nd Class Brown Belt'), ('Black Belt', 'Black Belt')], max_length=128),
        ),
    ]
