# Generated by Django 5.2.14 on 2026-05-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorrating',
            name='discipline_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instructorrating',
            name='kata_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instructorrating',
            name='kumite_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
