# Generated by Django 6.0.4 on 2026-05-25 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_alter_instructorrating_discipline_score_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parentstudent',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='parentstudent',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='parentstudent',
            name='added_at',
        ),
        migrations.RemoveField(
            model_name='parentstudent',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='parentstudent',
            name='is_primary_contact',
        ),
    ]
