# Generated by Django 6.0.4 on 2026-05-26 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_alter_parentstudent_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SparringMatch',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=32)),
                ('matchmaking_type', models.CharField(choices=[('automated', 'Automated'), ('manual', 'Manual')], default='manual', max_length=32)),
                ('score_a', models.IntegerField(default=0)),
                ('score_b', models.IntegerField(default=0)),
                ('duration_minutes', models.IntegerField(default=2)),
                ('match_date', models.DateField()),
                ('match_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('height_diff', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight_diff', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('age_diff', models.IntegerField(blank=True, null=True)),
                ('belt_diff', models.IntegerField(blank=True, null=True)),
                ('same_sex', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sparring_matches_managed', to=settings.AUTH_USER_MODEL)),
                ('student_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sparring_matches_as_a', to='students.student')),
                ('student_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sparring_matches_as_b', to='students.student')),
            ],
            options={
                'ordering': ['-match_date', '-created_at'],
                'indexes': [models.Index(fields=['match_date', 'status'], name='students_sp_match_d_9e7381_idx'), models.Index(fields=['student_a', 'match_date'], name='students_sp_student_31aef3_idx'), models.Index(fields=['student_b', 'match_date'], name='students_sp_student_312a29_idx'), models.Index(fields=['status'], name='students_sp_status_91684f_idx')],
            },
        ),
    ]
