# Generated by Django 5.2.14 on 2026-05-31 21:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_alter_instructorrating_scores_non_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parentstudent',
            options={'ordering': ['-added_at']},
        ),
        migrations.AlterUniqueTogether(
            name='parentstudent',
            unique_together={('parent', 'student')},
        ),
    ]
