from django.contrib import admin
from .models import (
    Student,
    PersonalInfo,
    Address,
    Contact,
    EmergencyContact,
    KarateBackground,
    Membership,
    FaceData,
    PoseTemplate,
    Session,
    Attendance,
    StanceEvaluation,
    Match,
    InstructorRating,
    KataRating,
    KumiteRating,
    PerformanceSummary,
    BeltProgressionIndicator,
    ProgressionInsight,
    Payment,
    Inventory,
    Sale,
    SystemID,
    Notification,
)

models_to_register = [
    Student,
    PersonalInfo,
    Address,
    Contact,
    EmergencyContact,
    KarateBackground,
    Membership,
    FaceData,
    PoseTemplate,
    Session,
    Attendance,
    StanceEvaluation,
    Match,
    InstructorRating,
    KataRating,
    KumiteRating,
    PerformanceSummary,
    BeltProgressionIndicator,
    ProgressionInsight,
    Payment,
    Inventory,
    Sale,
    SystemID,
    Notification,
]

for model in models_to_register:
    admin.site.register(model)
